#!/bin/bash

#run this file first to setup the directory


cd ../

base_dir="./template"
file_of_concern="constant/transportProperties"
file_DT_values="./Data/DT_values"
file_names_cases="names-cases.txt"

# Open file_DT_values on file descriptor 3
exec 3< "$file_DT_values"

while read nom && read DT <&3; do
	if [[ ! -d "${nom}" ]]; then
    	    cp -r "${base_dir}" "${nom}"
	fi

	cd "${nom}"
	foamDictionary ${file_of_concern} -entry DT -set ${DT}
	cd ../
	
done < ${file_names_cases}

echo "Paramter Values Set! Ready for generating the snaps!"



