#!/bin/bash

#run this file first to setup the directory
# then run runNtimes file

solution_space="../../OF_cases/td_heat_conduction"
base_dir="$solution_space/template"
file_dir="constant/transportProperties"

while read DT; do
	if [[ ! -d "$solution_space/$DT" ]]; then	
		cp -r "$base_dir" "$solution_space/$DT" 
	fi
	transportProperties="$solution_space/$DT/$file_dir"
	while IFS= read -r line; do
		 
		 if [[ "$line" =~ ^DT ]]; then
		 	line="DT    $DT;"
		 fi
		 echo "$line" >> "$solution_space/$DT/constant/newTP"
	done < $transportProperties
	
	 rm $transportProperties
	 mv "$solution_space/$DT/constant/newTP" "$solution_space/$DT/constant/transportProperties"
	
done < $solution_space/DT_values

echo "Performed the Task"



