#!/bin/bash

#prepared by Mahmudul Hasan Tamim (mht@tamu.edu)

# ensure that the script exits immediately if a command within exits with a non-zero status
set -e

#define the Data file
#DataFile="./Data/data.csv"

# define the directory where different cases are kept
case_space="./case_space"

if [[ -d "${case_space}" ]]; then
    rm -r "${case_space}"
    echo "Deleted case_space"
else
   echo "${case_space} doesn't exist."
fi



