#!/bin/bash
base_dir="$(pwd)/solution-space/HeatPlateBoundaryTimeDependent"
file_dir="/constant/transportProperties"

while read DT; do
	if [[ ! -d "./solution-space/$DT" ]]; then	
		cp -r "$base_dir" "./solution-space/$DT" 
	fi
	transportProperties="./solution-space/$DT$file_dir"
	while IFS= read -r line; do
		 
		 if [[ "$line" =~ ^DT ]]; then
		 	line="DT    $DT;"
		 fi
		 echo "$line" >> "./solution-space/$DT/constant/newTP"
	done < $transportProperties
	
	 rm $transportProperties
	 mv "./solution-space/$DT/constant/newTP" "./solution-space/$DT/constant/transportProperties"
	
done < DT_values

echo "Performed the Task"



