#!/bin/bash

# run this file to remove all the snapshots generated for different DT values

solution_space="../../snapshots/td_heat_conduction"
# file_dir="/constant/transportProperties"

while read DT; do
	# if [[ ! -d "$DT" ]]; then	
	#	cp -r "$base_dir" "$DT" 
	# fi
	# rm "./solution-space/$DT/constant/newTP"
	
	if [[ -d "$solution_space/$DT" ]]; then	
		rm -r "$solution_space/$DT" 
	fi
	
done < $solution_space/DT_values

echo "Performed the Task"



