#!/bin/bash

# first, run fix-space file

cases_dir=${1}
file_names_cases=${2}
from_case_dir_to_base_dir=$(pwd) 
case_space=${3}


if [[ ! -d ${case_space} ]]; then

  echo "Error: case-space directory is not found."
  exit 1 
 
fi


while read nom; do
	
	case_dir="${case_space}/${nom}"
	cd $case_dir
	applicationName=$(foamDictionary -entry application -value system/controlDict)
	$applicationName > case-run.log 2>&1
	cd $from_case_dir_to_base_dir
done < ${file_names_cases}

echo "Snaps generated!"



