#!/bin/bash

# copy the template to create different cases
source fix-space ../

# change directory to the bash directory of the given cases-directory
# then run the case-specific set-parameter-value script

./set-up-case

# after the parameter values have been set run simulation for each case
./runNtimes ${cases_dir} ${file_names_cases} ${case_space}





