#!/bin/bash

#run this file first to setup the directory


cd ../

base_dir="./template"
file_of_concern="constant/transportProperties"
file_DT_values="./Data/DT_values"
file_names_cases="names-cases.txt"
case_space="./case_space"

# Open file_DT_values on file descriptor 3
exec 3< "$file_DT_values"

while read nom && read DT <&3; do
	if [[ ! -d "${nom}" ]]; then
    	    cp -r "${base_dir}" "${case_space}/${nom}"
	fi
	(
	    cd "${case_space}/${nom}"
	    foamDictionary ${file_of_concern} -entry DT -set ${DT}
	    blockMesh > case-blockmesh.log 2>&1
	)
	
done < ${file_names_cases}

echo "Paramter Values Set! Mesh generated! Ready for generating the snaps!"



