#!/bin/bash

# run this file with the path to the set of openFoam cases directory
# run this file to remove all the snapshots generated for different parameter values

cases_dir=${1}

cases_dir="${cases_dir%/}"

file_names_cases="${cases_dir}/names-cases.txt"

while read nom; do
	
	case_dir="${cases_dir}/${nom}"
	if [[ -d "${case_dir}" ]]; then	
		rm -r "${case_dir}" 
	fi
	
done < ${file_names_cases}

echo "Removed all snaps!"



