#!/bin/bash

# first, run fix-space file

cases_dir=${1}
file_names_cases=${2}
from_case_dir_to_base_dir=$(pwd) 


while read nom; do
	
	case_dir="${cases_dir}/${nom}"
	cd $case_dir
	blockMesh > case-blockmesh.log 2>&1
	laplacianFoam > case-run.log 2>&1
	cd $from_case_dir_to_base_dir
done < ${file_names_cases}

echo "Snaps generated!"



